Added Detection for Missing values.conf File

diff --git a/updateandrun b/updateandrun
--- a/updateandrun
+++ b/updateandrun
@@ -4,13 +4,9 @@ cd "$(dirname "${BASH_SOURCE[0]}")"
 
 source values.conf
 
-if [ ! -f values.conf ] || [ "$(curl -s https://raw.githubusercontent.com/actualaardvark/bashsetupscriptrepo/main/values.conf)" != "$(cat values.conf)" ]; then
-	echo "Configuration file out of date"
-	curl -s "https://raw.githubusercontent.com/actualaardvark/bashsetupscriptrepo/main/values.conf" > values.conf
-	sh updateandrun
-	exit 1
-else
-	echo "Configuration file is up to date"
+if [ ! -f values.conf ]; then
+    echo "Invalid or Missing Config File. Obtain a Valid One from Github."
+    exit 1
 fi
 
 updateconfigfile(){
