Revert "E"
This reverts commit e1023d4b2336235b9efb1fcb434548d9c43e3945.

diff --git a/updateandrun b/updateandrun
--- a/updateandrun
+++ b/updateandrun
@@ -3,12 +3,54 @@
 cd "$(dirname "${BASH_SOURCE[0]}")"
 
 source values.conf
-source updateonly.sh
 
 migratepasswordfile(){
     if [ -f password.txt ]; then
         cat password.txt > password.conf
         rm password.txt
+    fi
+}
+
+checkformissingconfig(){
+    if [ ! -f values.conf ]; then
+        echo "Invalid or Missing Config File. Obtain a Valid One from Github."
+        exit 1
+    fi
+}
+
+downloadstructureimage(){
+    curl -s https://raw.githubusercontent.com/actualaardvark/bashsetupscriptrepo/$gitupdatebranch/structure.conf > structure.conf
+    filestodownload=()
+    ishidden="false"
+    while IFS= read -r line; do
+        filestodownload+=("$line")
+    done < "structure.conf"
+    for ((i = 0; i < ${#filestodownload[@]}; i++)); do
+        if [ ${filestodownload[$i]} = '#hide' ]; then
+            ishidden="true"
+        else
+            downloadedfile=${filestodownload[$i]}
+            if [ ! -f $downloadedfile ]; then
+                if [[ $downloadedfile == *"/"* ]]; then
+                    mkdir -p "${downloadedfile%/*}" && touch "$downloadedfile"
+                else
+                    touch "$downloadedfile"
+                fi
+            fi
+            curl -s  https://raw.githubusercontent.com/actualaardvark/bashsetupscriptrepo/$gitupdatebranch/${filestodownload[$i]} > ${filestodownload[$i]}
+            if [[ $ishidden == "true" ]]; then
+                chflags hidden ${filestodownload[$i]}
+                ishidden=false
+            fi
+            chmod +x ${filestodownload[$i]}
+        fi
+    done
+}
+
+checknetworkconnection(){
+    if [[ $(ping -q -c1 $connectioncheckurl &>/dev/null && echo online || echo offline) == "offline" ]]; then
+        echo "No Network Connection"
+        exit 1
     fi
 }
 
