cd and quote fixes

diff --git a/Additional-Scripts/Lab-Rename b/Additional-Scripts/Lab-Rename
--- a/Additional-Scripts/Lab-Rename
+++ b/Additional-Scripts/Lab-Rename
@@ -1,10 +1,10 @@
 #!/bin/bash
 
-echo "DO NOT run this script on a non-ILab device. Script will run in 5 seconds."
+echo "DO NOT run this script on a non-ILab device. Script will run in 5 seconds. ctrl + c to exit"
 
 echo "5" && sleep 1 && echo 4 && sleep 1 && echo 3 && sleep 1 && echo 2 && sleep 1 && echo 1 && sleep 1 && echo "Running..."
 
-cd "$(dirname "${BASH_SOURCE[0]}")/.."
+cd "$(dirname "${BASH_SOURCE[0]}")" || echo "changing directory failed" && exit
 
 source values.conf
 source update.sh
